import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home/route.tsx"),
  route("intro", "routes/intro/route.tsx"),
  route("about", "routes/about/route.tsx"),
  route("faq", "routes/faq/route.tsx"),
  route("practice", "routes/practice/route.tsx"),
  route("announce", "routes/announce/route.tsx"),
  route("village-list", "routes/village-list/route.tsx"),
  route("village/:villageId/message", "routes/village-message/route.tsx"),
  route("village/:villageId/scrap", "routes/village-scrap/route.tsx"),
  route("village/:villageId/report", "routes/village-report/route.tsx"),
  route("village/:villageId/day?/:day?", "routes/village/route.tsx"),
  route("new-village", "routes/new-village/route.tsx"),
  route("village/:villageId/settings", "routes/village-settings/route.tsx"),
  route("skill", "routes/skill/route.tsx"),
  route("rule", "routes/rule/route.tsx"),
  route("chara-group", "routes/chara-group/route.tsx"),
  route("chara-group/:id", "routes/chara-group-detail/route.tsx"),
  route("favorite-charas", "routes/favorite-charas/route.tsx"),
  route("random-message", "routes/random-message/route.tsx"),
  route("new-random-keyword", "routes/new-random-keyword/route.tsx"),
  route("random-keyword/:id", "routes/random-keyword/route.tsx"),
  route("archives/april-20240401", "routes/archives/april-20240401/route.tsx"),
  route("archives/april-20250401", "routes/archives/april-20250401/route.tsx"),
  route("archives/april-20250402", "routes/archives/april-20250402/route.tsx"),
  route("archives/april-20260401", "routes/archives/april-20260401/route.tsx"),
  route("user-list", "routes/user-list/route.tsx"),
  route("user/:name", "routes/user-profile/route.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("change-password", "routes/change-password.tsx"),
  // 外部公開 API (URL 変更不可) を backend へ素通しするリソースルート群。
  // 同一モジュールを共有するため id を明示する (routes/legacy-api/route.ts)
  route("recruiting", "routes/legacy-api/route.ts", { id: "legacy-recruiting" }),
  route("village-record/list", "routes/legacy-api/route.ts", { id: "legacy-village-record-list" }),
  route("village-record/latest-vid", "routes/legacy-api/route.ts", {
    id: "legacy-village-record-latest-vid",
  }),
  route("skill/list", "routes/legacy-api/route.ts", { id: "legacy-skill-list" }),
  route("api/village/:villageId", "routes/legacy-api/route.ts", { id: "legacy-api-village" }),
  route("api/village-list", "routes/legacy-api/route.ts", { id: "legacy-api-village-list" }),
] satisfies RouteConfig;
