import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home/route.tsx"),
  route("intro", "routes/intro/route.tsx"),
  route("about", "routes/about/route.tsx"),
  route("faq", "routes/faq/route.tsx"),
  route("practice", "routes/practice/route.tsx"),
  route("announce", "routes/announce/route.tsx"),
  route("village-list", "routes/village-list/route.tsx"),
  route("new-village", "routes/new-village/route.tsx"),
  route("skill", "routes/skill/route.tsx"),
  route("rule", "routes/rule/route.tsx"),
  route("chara-group", "routes/chara-group/route.tsx"),
  route("chara-group/:id", "routes/chara-group-detail/route.tsx"),
  route("random-message", "routes/random-message/route.tsx"),
  route("new-random-keyword", "routes/new-random-keyword/route.tsx"),
  route("random-keyword/:id", "routes/random-keyword/route.tsx"),
  route("archives/april-20250401", "routes/archives/april-20250401/route.tsx"),
  route("archives/april-20250402", "routes/archives/april-20250402/route.tsx"),
  route("archives/april-20260401", "routes/archives/april-20260401/route.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("mypage", "routes/mypage.tsx"),
  route("change-password", "routes/change-password.tsx"),
] satisfies RouteConfig;
